apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: greetings
spec:
  organization: ORGANIZATION_NAME
  token:
    secretKeyRef:
      name: tfc-operator
      key: token
  destroyOnDeletion: true
  module:
    source: "terraform-aws-modules/sqs/aws"
    version: "3.5.0"
  outputs:
    - name: sqs_queue_id
  variables:
    - name: name
    - name: fifo_queue
  workspace:
    name: greetings