apiVersion: app.terraform.io/v1alpha2
kind: Module
metadata:
  name: greetings
spec:
  organization: hashicorp-training
  token:
    secretKeyRef:
      name: terraformrc
      key: token
  destroyOnDeletion: true
  module:
    source: "terraform-aws-modules/sqs/aws"
    version: "4.0.1"
  outputs:
    - name: queue_id
  variables:
    - name: name
    - name: fifo_queue
  workspace:
    name: greetings